// <auto-generated />
namespace bazy_ostateczne.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class corect : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(corect));
        
        string IMigrationMetadata.Id
        {
            get { return "201705220725490_corect"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
